### ISSUE TITLE
what does 'aspect' refer to?

### ISSUE THREAD

**Issue by laurianvm** [fair-ease/py-udal-mgo#2]
Dear David & Cymon, 

What does 'aspect' refer to [here](https://github.com/fair-ease/py-udal-mgo/blob/452d66b552f629d53bb27b72c4bc9f16c5b4c1b0/mgo/namedqueries.py#L10C47-L10C102)?
or to which column of the *.go data files does this refer to? sub_process or process?

(e.g. see this column header is currently used during triple generation: https://github.com/emo-bon/analysis-results-uplifting-docker/blob/46d45ae43d5bdce972f6b3daba2f747bb59863da/work.yml#L42)

**Comment by palec87** [comment]
Hi Laurian,

we agreed with @cymon that column names
"id, name, aspect, abundance" correspond to "ID,sub_process,process,abundance" in this exact order. Example of EBI [here](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0005634/complete) shows that `name` and `aspect` are the correct ontologies and uplifting docker needs to change.

The same applies to go_slim tables.

**Comment by palec87** [comment]
Other comments to this part of uplift

- `go_slim` is missing with the same fields as `go`
- SSU, whichis the same structure as LSU is missing

```
subyt:
  - extra_sources:
      go_annotations:
        path: ./functional-annotation/DBB.merged.summary.go
        mime: text/csv
        header: ID,sub_process,process,abundance
      ips_annotations: 
        path: ./functional-annotation/DBB.merged.summary.ips
        mime: text/csv
        header: Abundance,ID,sequence_domain_region_name
      kegg_annotations: 
        path: ./functional-annotation/DBB.merged.summary.ko
        mime: text/csv
        header: Abundance,ID,name
      pfam_annotations: 
        path: ./functional-annotation/DBB.merged.summary.pfam
        mime: text/csv
        header: Abundance,ID,name
      eggnog_annotations: 
        path: ./functional-annotation/DBB.merged.emapper.summary.eggnog
        mime: text/csv
        header: Abundance,ID,name
    sink: !resolve ./{GENOSCOPE_ID}/functional-annotation
    template_name: functional-annotation.ldt.ttl
    mode: no-it
  - source: 
      path: ./taxonomy-summary/LSU/DBH.merged_LSU.fasta.mseq.csv
      mime: text/csv
      header: OTU_ID,LSU_rRNA,taxonomy,taxid
    sink: !resolve ./{GENOSCOPE_ID}/taxonomy-summary
    template_name: taxon-info.ldt.ttl
```

For the ips, kegg and pfam, I actually change the order of the columns to put abundance as a last one
1. ips: 'accession', 'description', 'abundance' in udal is in the uplifter terms "ID,name,Abundance", therefore uplifter should change to **abundance,accession,description**
2. ko: 'entry', 'name', 'abundance' in udal is in the uplifter "ID,name,Abundance", therefore change to **abundance,entry,name**
3. pfam: same as ko, 'entry', 'name', 'abundance' in udal is "ID,name,Abundance", therefore change to **abundance,entry,name**

@cymon If you think, that putting abundance as last column compared to raw outpus is not a good idea for the combined tables (my idea was to match the go/go_slim appearance), I can change it for the combined_table generation. This is super simple, but sooner it is settled the better.
